[project]
name = "backend"
version = "0.1.0"
description = "FastAPI project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiomqtt>=2.5.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "msgpack>=1.2.2",
    "sqlmodel>=0.0.39",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
